//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_job_posts
    {
        public int id { get; set; }
        public string CMRole { get; set; }
        public string CMName { get; set; }
        public string CMLocation { get; set; }
        public string CMMode { get; set; }
        public string CMPay { get; set; }
        public string CMLink { get; set; }
        public byte[] CMImage { get; set; }
    }
}
