//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_jobseekers_profile
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Profession { get; set; }
        public string Bio { get; set; }
        public string Location { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Education { get; set; }
        public string Skills { get; set; }
        public string SocialMedia { get; set; }
        public byte[] Image { get; set; }
        public bool IsProfileCreated { get; set; }
    }
}
