//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_college_events
    {
        public int id { get; set; }
        public string IName { get; set; }
        public string IWinner { get; set; }
        public string IAbout { get; set; }
        public string ITech { get; set; }
        public string ILink { get; set; }
    }
}
