//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employer_profile
    {
        public int id { get; set; }
        public string CName { get; set; }
        public string CBio { get; set; }
        public string CLocation { get; set; }
        public string CEmail { get; set; }
        public string CIndustry { get; set; }
        public byte[] CImage { get; set; }
        public string CSocialMedia { get; set; }
    }
}
