//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_colleges_profile
    {
        public int id { get; set; }
        public string ColName { get; set; }
        public string ColEmail { get; set; }
        public string ColAbout { get; set; }
        public string ColLocation { get; set; }
        public string ColURL { get; set; }
        public byte[] ColImage { get; set; }
    }
}
