//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerConnect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userRole
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public string Role { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
    }
}
